[package]
authors = ['Reef Finance <https://reef.finance>']
build = 'build.rs'
description = 'Reef Substrate Node'
edition = '2018'
homepage = 'https://reef.finance'
license = 'Unlicense'
name = 'reef-node'
repository = 'https://github.com/reef-defi/reef-chain'
version = '3.0.0'

[[bin]]
name = 'reef-node'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = '3.0.0'

[dependencies]
hex-literal = "0.3.1"
jsonrpc-core = '15.1.0'
structopt = '0.3.8'
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"

# Substrate dependencies
frame-benchmarking = '3.0.0'
frame-benchmarking-cli = '3.0.0'
pallet-transaction-payment-rpc = '3.0.0'
sc-chain-spec = { version = "3.0.0" }
sc-basic-authorship = '0.9.0'
sc-cli = { features = ['wasmtime'], version = '0.9.0' }
sc-client-api = '3.0.0'
sc-executor = { features = ['wasmtime'], version = '0.9.0' }
sc-rpc = '3.0.0'
sc-rpc-api = '0.9.0'
sc-service = { features = ['wasmtime'], version = '0.9.0' }
sc-transaction-pool = '3.0.0'
sc-telemetry = { version = "3.0.0" }
sp-std = { version = "3.0.0" }
sp-api = '3.0.0'
sp-block-builder = '3.0.0'
sp-blockchain = '3.0.0'
sp-core = '3.0.0'
sp-inherents = '3.0.0'
sp-runtime = '3.0.0'
sp-transaction-pool = '3.0.0'
substrate-frame-rpc-system = '3.0.0'

sc-keystore = { version = "3.0.0" }
sp-keystore = { version = "0.9.0" }

sp-finality-grandpa = '3.0.0'
sc-finality-grandpa = '0.9.0'
sc-finality-grandpa-rpc = { version = "0.9.0" }

sp-consensus = '0.9.0'
sp-consensus-babe = '0.9.0'
sc-consensus = '0.9.0'
sc-consensus-babe = '0.9.0'
sc-consensus-babe-rpc = { version = "0.9.0" }
sc-consensus-manual-seal = { version = "0.9.0" }
sc-consensus-epochs = { version = "0.9.0" }
sc-consensus-slots = { version = "0.9.0" }


module-evm = { path = "../modules/evm" }
module-evm-rpc-runtime-api = { path = "../modules/evm/rpc/runtime_api" }
evm-rpc = { path = "../modules/evm/rpc" }

reef-primitives = { path = "../primitives" }
inspect = { package = "reef-inspect", path = "../inspect" }

# runtime
reef-runtime = { path = '../runtime', version = '3.0.0' }

[features]
default = []
runtime-benchmarks = ['reef-runtime/runtime-benchmarks']
with-ethereum-compatibility = [
	"reef-runtime/with-ethereum-compatibility"
]
